services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=backend:9091
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build:
      context: .
      target: builder
    stop_signal: SIGINT
    env_file:
      - .env
    environment:
      - FLASK_SERVER_PORT=9091
    volumes:
      - .:/src
    restart: unless-stopped
    depends_on:
      - mongo

  telegram_bot:
    build:
      context: .
      target: builder # assuming the backend Dockerfile is Dockerfile
    stop_signal: SIGINT
    command: python telebot.py
    volumes:
      - .:/src
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongo
      - backend

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db

  mongo-express:
    env_file:
      - .env
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo

volumes:
  mongo_data:
